### ISSUE TITLE
ABM

### ISSUE THREAD

**Issue by Grossam** [Mynetest/metal_carpentry#1]
Mon essai d'ABM ne semble par marcher. C'est pourtant un copy-paste de l'exemple donné par Upsi ?

**Comment by paly2** [comment]
L'itemstring du bloc de fer est `default:steelblock`, pas `default:steel_block`. C'est peut-être moi qui l'avais mal écrit dans mon exemple

**Comment by Grossam** [comment]
C'était bêtement ça ! Je me fais toujours avoir par cet underscore manquant… Maintenant ça marche !
